spring:
  application:
    name: sqcs-server
  security:
    user:
      name: "admin"
      password: "admin"

  mail:
    host: "mail.purang.com"
    username: "autotest@purang.com"
    password: "Purang123"

  boot:
    admin:
      ui:
        title: 监控中心
        brand: <img src="assets/img/icon-spring-boot-admin.svg"><span>监控中心</span>
        cache:
          no-cache: true

admin:
  notify:
    mail:
      to: ${admin.mail.to}
      from: autotest@purang.com
      template: classpath:/META-INF/status-changed.html

server:
  port: 8009
  servlet:
    context-path: /octopus

logging:
  level:
    com: info
    de: info

octopus:
  log:
    path: /sepp/log/octopus

system:
  metric:
    monitor:
      disk: 0.8

